version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      - sphinx-apidoc -e -force --no-toc --module-first -o docs/api sequence

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - htmlzip

python:
  install:
    - requirements: docs/requirements.in
    - method: pip
      path: .
  system_packages: false
