version: 2

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - htmlzip

python:
  install:
    - requirements: requirements-doc.txt
    - requirements: requirements.txt
    - method: pip
      path: .
  system_packages: false

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    pre_build:
      - sphinx-apidoc -e -force --no-toc --module-first -o docs/api sequence
