name: Documentation

on: [push, pull_request]

jobs:
    build:
        # We want to run on external PRs, but not on our own internal PRs as they'll be run
        # by the push to the branch. Without this if check, checks are duplicated since
        # internal PRs match both the push and pull_request events.
        if:
          github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
          github.repository
    
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
        
              - name: Set up Python 3.9
                uses: actions/setup-python@v2
                with:
                  python-version: 3.9
        
              - name: Install dependencies
                run: |
                  python -m pip install --upgrade pip setuptools wheel
                  conda install --file=requirements.txt -c conda-forge
                  python -m pip install -e "."
                  python -m pip install -r "requirements-docs.txt"
              - name: Build documentation
                run: make -C docs clean html            
