name: Build/Test CI

on: [push, pull_request]

jobs:
  build:
    if: |
      github.event_name == 'push' ||
      github.event.pull_request.head.repo.full_name != github.repository

    name: Build source distribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build wheel
        run: |
          pip install nox
          nox -s build

      - uses: actions/upload-artifact@v4
        with:
          name: build-sdist
          path: ${{ github.workspace }}/dist/*.whl

  test:
    needs: build
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]
        exclude:
          # This is tested in the coverage job
          - os: ubuntu-latest
            python-version: "3.12"

    steps:
      - uses: actions/checkout@v4

      - name: Use Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/download-artifact@v4
        name: Download build artifacts
        with:
          pattern: "build-*"
          merge-multiple: true
          path: ${{ github.workspace }}/dist

      - name: Install dependencies
        run: pip install nox

      - name: Test
        run: |
          nox -s test

      - name: Test the cli
        run: |
          nox -s test-cli

  coverage:
    needs: build
    name: Run coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: actions/download-artifact@v4
        name: Download build artifacts
        with:
          pattern: "build-*"
          merge-multiple: true
          path: ${{ github.workspace }}/dist

      - name: coverage
        env:
          COVERAGE_CORE": "sysmon"
        run: |
          pip install nox
          nox --verbose -s coverage

      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true
          flag-name: py3.12-ubuntu-latest
          debug: true
